"""
Constants file
"""

# have the name to ticker mapping in memory for now, not sure if any free apis provide the information
COMPANIES = {
    "Nvidia": "NVDA",
    "Microsoft": "MSFT",
    "Apple Inc.": "AAPL",
    "Amazon": "AMZN",
    "Meta Platforms": "META",
    "Broadcom": "AVGO",
    "Alphabet Inc. (Class A)": "GOOGL",
    "Tesla, Inc.": "TSLA",
    "Alphabet Inc. (Class C)": "GOOG",
    "Berkshire Hathaway": "BRK.B",
    "Oracle Corporation": "ORCL",
    "JPMorgan Chase": "JPM",
    "Walmart": "WMT",
    "Lilly (Eli)": "LLY",
    "Visa Inc.": "V",
    "Netflix": "NFLX",
    "Mastercard": "MA",
    "ExxonMobil": "XOM",
    "Johnson & Johnson": "JNJ",
    "Palantir Technologies": "PLTR",
    "Costco": "COST",
    "AbbVie": "ABBV",
    "Home Depot (The)": "HD",
    "Bank of America": "BAC",
    "Advanced Micro Devices": "AMD",
    "Procter & Gamble": "PG",
    "UnitedHealth Group": "UNH",
    "GE Aerospace": "GE",
    "Chevron Corporation": "CVX",
    "Coca-Cola Company (The)": "KO",
    "Cisco": "CSCO",
    "IBM": "IBM",
    "Wells Fargo": "WFC",
    "T-Mobile US": "TMUS",
    "Philip Morris International": "PM",
    "Morgan Stanley": "MS",
    "Goldman Sachs": "GS",
    "Salesforce": "CRM",
    "Caterpillar Inc.": "CAT",
    "Abbott Laboratories": "ABT",
    "American Express": "AXP",
    "Micron Technology": "MU",
    "RTX Corporation": "RTX",
    "Merck & Co.": "MRK",
    "McDonald's": "MCD",
    "Linde plc": "LIN",
    "PepsiCo": "PEP",
    "AppLovin Corporation": "APP",
    "Thermo Fisher Scientific": "TMO",
    "Walt Disney Company (The)": "DIS",
    "Uber": "UBER",
    "ServiceNow": "NOW",
    "Arista Networks": "ANET",
    "AT&T": "T",
    "Intuit": "INTU",
    "BlackRock": "BLK",
    "Citigroup": "C",
    "GE Vernova": "GEV",
    "Intel": "INTC",
    "Applied Materials": "AMAT",
    "Qualcomm": "QCOM",
    "NextEra Energy": "NEE",
    "Lam Research": "LRCX",
    "Booking Holdings": "BKNG",
    "Charles Schwab Corporation": "SCHW",
    "Verizon": "VZ",
    "Boeing": "BA",
    "Texas Instruments": "TXN",
    "Amgen": "AMGN",
    "TJX Companies": "TJX",
    "Intuitive Surgical": "ISRG",
    "Amphenol": "APH",
    "Accenture": "ACN",
    "Danaher Corporation": "DHR",
    "S&P Global": "SPGI",
    "Eaton Corporation": "ETN",
    "Gilead Sciences": "GILD",
    "Palo Alto Networks": "PANW",
    "Adobe Inc.": "ADBE",
    "Pfizer": "PFE",
    "Boston Scientific": "BSX",
    "Stryker Corporation": "SYK",
    "Progressive Corporation": "PGR",
    "KLA Corporation": "KLAC",
    "Union Pacific Corporation": "UNP",
    "Capital One": "COF",
    "Lowe's": "LOW",
    "Honeywell": "HON",
    "CrowdStrike": "CRWD",
    "Robinhood Markets, Inc.": "HOOD",
    "Blackstone Inc.": "BX",
    "Medtronic": "MDT",
    "Constellation Energy": "CEG",
    "Deere & Company": "DE",
    "DoorDash": "DASH",
    "Lockheed Martin": "LMT",
    "Analog Devices": "ADI",
    "Automatic Data Processing": "ADP",
    "Chubb Limited": "CB",
    "Welltower": "WELL",
    "ConocoPhillips": "COP",
    "Altria": "MO",
    "Comcast": "CMCSA",
    "Southern Company": "SO",
    "KKR": "KKR",
    "Vertex Pharmaceuticals": "VRTX",
    "Prologis": "PLD",
    "Dell Technologies": "DELL",
    "Marsh McLennan": "MMC",
    "Nike, Inc.": "NKE",
    "CVS Health": "CVS",
    "Newmont": "NEM",
    "CME Group": "CME",
    "Duke Energy": "DUK",
    "HCA Healthcare": "HCA",
    "McKesson Corporation": "MCK",
    "Trane Technologies": "TT",
    "Parker Hannifin": "PH",
    "Coinbase Global": "COIN",
    "Starbucks": "SBUX",
    "Intercontinental Exchange": "ICE",
    "Cadence Design Systems": "CDNS",
    "General Dynamics": "GD",
    "Bristol Myers Squibb": "BMY",
    "Northrop Grumman": "NOC",
    "Waste Management": "WM",
    "O'Reilly Auto Parts": "ORLY",
    "American Tower": "AMT",
    "Moody's Corporation": "MCO",
    "Royal Caribbean Group": "RCL",
    "Synopsys": "SNPS",
    "Sherwin-Williams": "SHW",
    "3M": "MMM",
    "Equinix": "EQIX",
    "Cigna": "CI",
    "Elevance Health": "ELV",
    "Mondelez International": "MDLZ",
    "Williams Companies": "WMB",
    "Howmet Aerospace": "HWM",
    "Ecolab": "ECL",
    "Aon": "AON",
    "Motorola Solutions": "MSI",
    "Cintas": "CTAS",
    "Arthur J. Gallagher & Co.": "AJG",
    "BNY Mellon": "BK",
    "Corning Inc.": "GLW",
    "TransDigm Group": "TDG",
    "Airbnb": "ABNB",
    "PNC Financial Services": "PNC",
    "Emerson Electric": "EMR",
    "U.S. Bancorp": "USB",
    "Marriott International": "MAR",
    "Illinois Tool Works": "ITW",
    "Vistra Corp.": "VST",
    "United Parcel Service": "UPS",
    "Apollo Global Management": "APO",
    "Republic Services": "RSG",
    "Johnson Controls": "JCI",
    "AutoZone": "AZO",
    "Fiserv": "FI",
    "CSX Corporation": "CSX",
    "PayPal": "PYPL",
    "Autodesk": "ADSK",
    "Monster Beverage": "MNST",
    "Norfolk Southern Railway": "NSC",
    "TE Connectivity": "TEL",
    "Fortinet": "FTNT",
    "Quanta Services": "PWR",
    "Zoetis": "ZTS",
    "Workday, Inc.": "WDAY",
    "United Rentals": "URI",
    "American Electric Power": "AEP",
    "Hilton Worldwide": "HLT",
    "Colgate-Palmolive": "CL",
    "Cencora": "COR",
    "Freeport-McMoRan": "FCX",
    "Kinder Morgan": "KMI",
    "Travelers Companies (The)": "TRV",
    "EOG Resources": "EOG",
    "Sempra": "SRE",
    "Regeneron Pharmaceuticals": "REGN",
    "Aflac": "AFL",
    "Digital Realty": "DLR",
    "Air Products": "APD",
    "Simon Property Group": "SPG",
    "Datadog": "DDOG",
    "Cummins": "CMI",
    "L3Harris": "LHX",
    "Truist Financial": "TFC",
    "Axon Enterprise": "AXON",
    "Roper Technologies": "ROP",
    "Marathon Petroleum": "MPC",
    "Chipotle Mexican Grill": "CMG",
    "FedEx": "FDX",
    "Allstate": "ALL",
    "NXP Semiconductors": "NXPI",
    "Realty Income": "O",
    "MetLife": "MET",
    "Becton Dickinson": "BDX",
    "General Motors": "GM",
    "Public Storage": "PSA",
    "Phillips 66": "PSX",
    "Dominion Energy": "D",
    "Nasdaq, Inc.": "NDAQ",
    "Idexx Laboratories": "IDXX",
    "Ross Stores": "ROST",
    "Valero Energy": "VLO",
    "Electronic Arts": "EA",
    "Paccar": "PCAR",
    "Fastenal": "FAST",
    "Carrier Global": "CARR",
    "Garmin": "GRMN",
    "Schlumberger": "SLB",
    "Xcel Energy": "XEL",
    "Exelon": "EXC",
    "Monolithic Power Systems": "MPWR",
    "Take-Two Interactive": "TTWO",
    "Seagate Technology": "STX",
    "Ford Motor Company": "F",
    "Block, Inc.": "XYZ",
    "Paychex": "PAYX",
    "CBRE Group": "CBRE",
    "Ameriprise Financial": "AMP",
    "D. R. Horton": "DHI",
    "American International Group": "AIG",
    "Baker Hughes": "BKR",
    "W. W. Grainger": "GWW",
    "Kroger": "KR",
    "Warner Bros. Discovery": "WBD",
    "ONEOK": "OKE",
    "Edwards Lifesciences": "EW",
    "Copart": "CPRT",
    "Corteva": "CTVA",
    "Entergy": "ETR",
    "MSCI": "MSCI",
    "Ametek": "AME",
    "Crown Castle": "CCI",
    "Occidental Petroleum": "OXY",
    "Diamondback Energy": "FANG",
    "Public Service Enterprise Group": "PEG",
    "Western Digital": "WDC",
    "eBay": "EBAY",
    "Vulcan Materials Company": "VMC",
    "ResMed": "RMD",
    "Kimberly-Clark": "KMB",
    "Target Corporation": "TGT",
    "Fair Isaac": "FICO",
    "Yum! Brands": "YUM",
    "Agilent Technologies": "A",
    "Martin Marietta Materials": "MLM",
    "Hershey Company (The)": "HSY",
    "Rockwell Automation": "ROK",
    "Delta Air Lines": "DAL",
    "Sysco": "SYY",
    "WEC Energy Group": "WEC",
    "Carnival": "CCL",
    "Cardinal Health": "CAH",
    "Consolidated Edison": "ED",
    "Hartford (The)": "HIG",
    "Live Nation Entertainment": "LYV",
    "Keurig Dr Pepper": "KDP",
    "Xylem Inc.": "XYL",
    "Charter Communications": "CHTR",
    "Prudential Financial": "PRU",
    "PG&E Corporation": "PCG",
    "Fidelity National Information Services": "FIS",
    "Otis Worldwide": "OTIS",
    "Microchip Technology": "MCHP",
    "IQVIA": "IQV",
    "Arch Capital Group": "ACGL",
    "Verisk Analytics": "VRSK",
    "EQT Corporation": "EQT",
    "Estée Lauder Companies (The)": "EL",
    "Wabtec": "WAB",
    "GE HealthCare": "GEHC",
    "Vici Properties": "VICI",
    "Hewlett Packard Enterprise": "HPE",
    "Willis Towers Watson": "WTW",
    "Humana": "HUM",
    "CoStar Group": "CSGP",
    "Cognizant": "CTSH",
    "Supermicro": "SMCI",
    "State Street Corporation": "STT",
    "Targa Resources": "TRGP",
    "NRG Energy": "NRG",
    "United Airlines Holdings": "UAL",
    "Las Vegas Sands": "LVS",
    "Raymond James Financial": "RJF",
    "DuPont": "DD",
    "Nucor": "NUE",
    "Kenvue": "KVUE",
    "Interactive Brokers Group": "IBKR",
    "Brown & Brown": "BRO",
    "Ventas": "VTR",
    "Ingersoll Rand": "IR",
    "EMCOR Group, Inc.": "EME",
    "Lennar": "LEN",
    "Extra Space Storage": "EXR",
    "Iron Mountain": "IRM",
    "Kraft Heinz": "KHC",
    "Archer Daniels Midland": "ADM",
    "W. R. Berkley Corporation": "WRB",
    "Tractor Supply": "TSCO",
    "Kellanova": "K",
    "DTE Energy": "DTE",
    "Old Dominion": "ODFL",
    "M&T Bank": "MTB",
    "Equifax": "EFX",
    "Atmos Energy": "ATO",
    "Keysight Technologies": "KEYS",
    "Ameren": "AEE",
    "Fifth Third Bancorp": "FITB",
    "PPL Corporation": "PPL",
    "American Water Works": "AWK",
    "Rollins, Inc.": "ROL",
    "Broadridge Financial Solutions": "BR",
    "FirstEnergy": "FE",
    "Eversource Energy": "ES",
    "Expedia Group": "EXPE",
    "Teledyne Technologies": "TDY",
    "Mettler Toledo": "MTD",
    "AvalonBay Communities": "AVB",
    "Synchrony Financial": "SYF",
    "General Mills": "GIS",
    "HP Inc.": "HPQ",
    "CenterPoint Energy": "CNP",
    "Dexcom": "DXCM",
    "Cboe Global Markets": "CBOE",
    "Veralto": "VLTO",
    "Cincinnati Financial": "CINF",
    "The Trade Desk, Inc.": "TTD",
    "Verisign": "VRSN",
    "Constellation Brands": "STZ",
    "Expand Energy": "EXE",
    "First Solar": "FSLR",
    "Ulta Beauty": "ULTA",
    "PTC Inc.": "PTC",
    "Northern Trust": "NTRS",
    "International Paper": "IP",
    "Leidos": "LDOS",
    "PulteGroup": "PHM",
    "NetApp": "NTAP",
    "Equity Residential": "EQR",
    "Tapestry, Inc.": "TPR",
    "Huntington Bancshares": "HBAN",
    "Steris": "STE",
    "T. Rowe Price": "TROW",
    "Williams-Sonoma": "WSM",
    "LabCorp": "LH",
    "Dollar General": "DG",
    "PPG Industries": "PPG",
    "Dover Corporation": "DOV",
    "Teradyne": "TER",
    "Insulet Corporation": "PODD",
    "Hubbell Incorporated": "HUBB",
    "CMS Energy": "CMS",
    "Regions Financial Corporation": "RF",
    "Tyler Technologies": "TYL",
    "Smurfit WestRock": "SW",
    "Citizens Financial Group": "CFG",
    "Jabil": "JBL",
    "Steel Dynamics": "STLD",
    "Darden Restaurants": "DRI",
    "Biogen": "BIIB",
    "Devon Energy": "DVN",
    "Church & Dwight": "CHD",
    "Loews Corporation": "L",
    "NVR, Inc.": "NVR",
    "Edison International": "EIX",
    "Quest Diagnostics": "DGX",
    "ON Semiconductor": "ON",
    "Texas Pacific Land Corporation": "TPL",
    "Global Payments": "GPN",
    "SBA Communications": "SBAC",
    "Lululemon Athletica": "LULU",
    "NiSource": "NI",
    "Waters Corporation": "WAT",
    "Corpay": "CPAY",
    "F5, Inc.": "FFIV",
    "CDW": "CDW",
    "Ralph Lauren Corporation": "RL",
    "KeyCorp": "KEY",
    "Halliburton": "HAL",
    "Zimmer Biomet": "ZBH",
    "Dollar Tree": "DLTR",
    "West Pharmaceutical Services": "WST",
    "Paramount Skydance Corp": "PSKY",
    "Packaging Corporation of America": "PKG",
    "Gartner": "IT",
    "Amcor": "AMCR",
    "Tyson Foods": "TSN",
    "Lennox International": "LII",
    "Jacobs Solutions": "J",
    "Genuine Parts Company": "GPC",
    "Trimble Inc.": "TRMB",
    "GoDaddy": "GDDY",
    "Pentair": "PNR",
    "Evergy": "EVRG",
    "Centene Corporation": "CNC",
    "Principal Financial Group": "PFG",
    "Aptiv": "APTV",
    "McCormick & Company": "MKC",
    "Coterra": "CTRA",
    "Alliant Energy": "LNT",
    "Weyerhaeuser": "WY",
    "Invitation Homes": "INVH",
    "Snap-on": "SNA",
    "Incyte": "INCY",
    "Erie Indemnity": "ERIE",
    "Southwest Airlines": "LUV",
    "Essex Property Trust": "ESS",
    "Fortive": "FTV",
    "Gen Digital": "GEN",
    "Best Buy": "BBY",
    "Bunge Global": "BG",
    "Mid-America Apartment Communities": "MAA",
    "Expeditors International": "EXPD",
    "International Flavors & Fragrances": "IFF",
    "TKO Group Holdings": "TKO",
    "Dow Inc.": "DOW",
    "Allegion": "ALLE",
    "Omnicom Group": "OMC",
    "LyondellBasell": "LYB",
    "Everest Group": "EG",
    "C.H. Robinson": "CHRW",
    "Clorox": "CLX",
    "Textron": "TXT",
    "Hologic": "HOLX",
    "Deckers Brands": "DECK",
    "Zebra Technologies": "ZBRA",
    "Kimco Realty": "KIM",
    "CF Industries": "CF",
    "Domino's": "DPZ",
    "Masco": "MAS",
    "Cooper Companies (The)": "COO",
    "Builders FirstSource": "BLDR",
    "J.B. Hunt": "JBHT",
    "Ball Corporation": "BALL",
    "Nordson Corporation": "NDSN",
    "Hormel Foods": "HRL",
    "Regency Centers": "REG",
    "Brown–Forman": "BF.B",
    "Alexandria Real Estate Equities": "ARE",
    "Universal Health Services": "UHS",
    "Healthpeak Properties": "DOC",
    "Fox Corporation (Class B)": "FOX",
    "Solventum": "SOLV",
    "Avery Dennison": "AVY",
    "Fox Corporation (Class A)": "FOXA",
    "IDEX Corporation": "IEX",
    "Franklin Resources": "BEN",
    "UDR, Inc.": "UDR",
    "Wynn Resorts": "WYNN",
    "Viatris": "VTRS",
    "Baxter International": "BAX",
    "Paycom": "PAYC",
    "Huntington Ingalls Industries": "HII",
    "Albemarle Corporation": "ALB",
    "Host Hotels & Resorts": "HST",
    "Assurant": "AIZ",
    "BXP, Inc.": "BXP",
    "Globe Life": "GL",
    "J.M. Smucker Company (The)": "SJM",
    "Pool Corporation": "POOL",
    "Camden Property Trust": "CPT",
    "Pinnacle West": "PNW",
    "FactSet": "FDS",
    "Dayforce": "DAY",
    "Jack Henry & Associates": "JKHY",
    "Akamai Technologies": "AKAM",
    "Skyworks Solutions": "SWKS",
    "Molina Healthcare": "MOH",
    "Revvity": "RVTY",
    "Norwegian Cruise Line Holdings": "NCLH",
    "Moderna": "MRNA",
    "Invesco": "IVZ",
    "AES Corporation": "AES",
    "Generac": "GNRC",
    "Hasbro": "HAS",
    "Stanley Black & Decker": "SWK",
    "Mosaic Company (The)": "MOS",
    "News Corp (Class A)": "NWSA",
    "Interpublic Group of Companies (The)": "IPG",
    "A. O. Smith": "AOS",
    "Align Technology": "ALGN",
    "Bio-Techne": "TECH",
    "Molson Coors Beverage Company": "TAP",
    "Campbell Soup Company": "CPB",
    "Lamb Weston": "LW",
    "DaVita": "DVA",
    "Conagra Brands": "CAG",
    "MGM Resorts": "MGM",
    "Federal Realty Investment Trust": "FRT",
    "Charles River Laboratories": "CRL",
    "EPAM Systems": "EPAM",
    "APA Corporation": "APA",
    "Match Group": "MTCH",
    "Henry Schein": "HSIC",
    "LKQ Corporation": "LKQ",
    "Mohawk Industries": "MHK",
    "Eastman Chemical Company": "EMN",
    "CarMax": "KMX",
    "News Corp (Class B)": "NWS",
}
